# Generated by Django 6.0.6 on 2026-06-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('statusAtivo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('pontos', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('pontos_maximo', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('totalAcertos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('palpite', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='api_apostas.usuario')),
            ],
        ),
    ]
